name: Hello World by sub_repository

on:
  push:
    # branches: [develop]
    paths:
      - "github_action_demo/sub_repository/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "sub_repository"

      - name: Say Hello By sub_repository
        run: echo "Hello, World!!! by sub_repository"
