name: Hello World by sub_repository

on:
  push:
    branches: [develop]
    paths: [sub_repository/**]

defaults:
  run:
    working-directory: sub_repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "sub_repository"

      - name: Say Hello By sub_repository
        run: echo "Hello, World!!! by sub_repository"
