name: Hello World by sub_repository

on:
  push:
    paths: [sub_repository/**]

defaults:
  run:
    working-directory: sub_repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: "sub_repository"

      - name: Say Hello By sub_repository on develop
        if: contains(toJSON(github.ref), 'develop')
        run: echo "Hello, World!!! by sub_repository on develop"

      - name: Say Hello By sub_repository on main
        if: contains(toJSON(github.ref), 'main')
        run: echo "Hello, World!!! by sub_repository on main"
